# Site
repository: benyazi/benyazi.github.io
# favicon: images/favicon.ico

# Personal info
name: Sergey Klabukov
title: Middle PHP developer
email: yo@benyazi.ru
website: https://benyazi.ru

# Social links
twitter_username: ben_yazi
github_username:  benyazi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ben_yazi
linkedin_username: sergeyklabukov
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: https://benyazi.ru/imgs/self_benyazi.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergey and I'm a middle PHP developer. I have 6+ year experience in PHP, I worked with a lot of frameworks (Symfony, Laravel, Yii, Phalcon, Kohana, CodeIgniter and etc). 

  I am most skilled in: <mark>PHP</mark> <mark>Symfony</mark> <mark>Laravel</mark>.

  Also I am working with: <mark>JS</mark> <mark>Vue.js</mark> <mark>Lua</mark> <mark>C#</mark> and <mark>more</mark>.

# Projects Section
#projects_title: "Проекты"

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in PHP and JS some of my other interests and hobbies are:
   - Gamedev
   - Movie science
   - Cap collecting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
